from __future__ import annotations

import os

import httpx
from fastapi import APIRouter, Depends, Request
from fastapi.responses import JSONResponse

from control_center.core.auth import require_permission

# PR A4 (Admin Console Capability Parity -- RAG/PubMed), reworked for
# omnibioai-rag's HIPAA-V2-001 R4/R6 authorization model.
#
# Every route here forwards the *caller's own* Authorization header to
# omnibioai-rag, unchanged. No shared/service credential is injected.
# omnibioai-rag no longer accepts one on any route: GET /v1/studies
# requires an IAM-verified JWT carrying dataset.read (and returns only the
# studies that caller's organization may see), and GET /v1/cache/stats
# requires an IAM-verified JWT carrying manage_all_orgs. RAG verifies the
# token itself (signature, expiry, revocation) and remains the sole
# authority on those two permissions -- this proxy makes no authorization
# decision about RAG data and never turns a RAG 401/403 into a success.
#
# Control Center's own gate is unchanged and still runs first:
# /rag/studies and /rag/cache-stats require platform.manage_infra (the same
# permission every hasAdminAccess()-gated Infra page requires) before any
# upstream call is made, so an unauthenticated or wrongly-permissioned
# caller never reaches RAG at all. That gate is control-center's own
# concern; a caller who passes it can still be refused by RAG (403 for a
# missing dataset.read / manage_all_orgs), and that refusal is relayed.
#
# GET /health has no auth requirement upstream and no control-center gate
# (a liveness probe, not RAG data); the caller's header is forwarded there
# too if present, which RAG ignores.
#
# Origin marker: a 401 relayed from RAG is indistinguishable, by status
# code and body shape, from control-center's own 401 for an invalid admin
# session -- but the two mean different things to the browser (only the
# latter should end the Admin Console session). Every response relayed from
# RAG therefore carries UPSTREAM_SERVICE_HEADER so the frontend can decide
# from structured data instead of matching error wording. A response
# generated by control-center itself (its own require_permission 401/403,
# or the 503 for an unreachable RAG) never carries it.
router = APIRouter()

RAG_URL = os.environ.get("RAG_URL", "http://rag:8096")

UPSTREAM_SERVICE_HEADER = "X-Upstream-Service"
UPSTREAM_SERVICE_NAME = "rag"

# Module-level singleton, not inlined into the route signatures below --
# ruff's B008 (this file is in ci.yml's scoped "Admin Console milestone"
# lint set, no extend-immutable-calls configured repo-wide) flags any
# function call in an argument default, Depends(...) itself included, not
# only fastapi's own allowlisted calls. Constructing it once here and
# referencing the variable as the default satisfies that rule exactly the
# way ruff's own B008 message recommends, with identical runtime
# behavior -- FastAPI resolves a Depends(...) sentinel by object identity,
# not by where it was constructed, and sharing one instance across both
# routes below is the normal, supported way to reuse a dependency.
_require_platform_manage_infra = Depends(require_permission("platform.manage_infra"))


async def _proxy(path: str, request: Request) -> JSONResponse:
    headers = {"Content-Type": "application/json"}
    auth_header = request.headers.get("authorization")
    if auth_header:
        headers["Authorization"] = auth_header

    try:
        # /rag/studies specifically: RAG caches this response (see
        # ragbio/cache/redis_cache.py's get_studies/set_studies), but a
        # cache miss (first call, or once per RAG_CACHE_TTL/1h window)
        # still takes RAG's own observed ~11s to scan its abstract
        # store -- the previous 10s timeout here 503'd that call
        # outright even though RAG would have answered a second later.
        # 20s gives that cold path real margin without the request
        # hanging indefinitely if RAG is genuinely down.
        async with httpx.AsyncClient(timeout=20) as client:
            r = await client.get(
                f"{RAG_URL}{path}",
                params=request.query_params,
                headers=headers,
            )
    except httpx.RequestError as e:
        return JSONResponse(
            {"error": f"rag-service unreachable: {type(e).__name__}: {e}"}, status_code=503,
        )

    try:
        payload = r.json()
    except ValueError:
        payload = {"error": "rag-service returned a non-JSON response"}
    return JSONResponse(
        payload,
        status_code=r.status_code,
        headers={UPSTREAM_SERVICE_HEADER: UPSTREAM_SERVICE_NAME},
    )


@router.get("/rag/studies")
async def list_studies_proxy(
    request: Request,
    _admin: dict = _require_platform_manage_infra,
) -> JSONResponse:
    return await _proxy("/v1/studies", request)


@router.get("/rag/cache-stats")
async def cache_stats_proxy(
    request: Request,
    _admin: dict = _require_platform_manage_infra,
) -> JSONResponse:
    return await _proxy("/v1/cache/stats", request)


@router.get("/rag/health")
async def health_proxy(request: Request) -> JSONResponse:
    return await _proxy("/health", request)
