"""GET /compliance/hipaa-report[/pdf|/csv] -- Basic HIPAA Compliance
Report (OmniBioAI Studio v0.8.0). Platform_admin-only for this version:
org_admin scoping is deferred to v0.9.0 -- two of the four sections'
sources (login events, the security-audit deny stream) have no org-scoped
read path today, and building one is a real backend change in
omnibioai-auth, not something this report's own router can paper over
(see compliance/service.py's module docstring for the full reasoning).

Every route: 1) requires manage_all_orgs (the same platform-admin bypass
permission every other /platform/* surface in this ecosystem already
uses -- auth/app/rbac.py::MANAGE_ALL_ORGS, reused verbatim, not
redefined); 2) reads-through the existing 1-hour-capable Redis cache
(analytics/cache.py -- this package doesn't own a second caching
mechanism); 3) delegates all aggregation to service.py -- no computation
happens in this file; 4) records a compliance_report_accessed audit
event on success (audit_log.py).

Pre-merge security review fix (2026-08-12): generated_by/generated_at are
deliberately NOT part of what _fetch_cached_report returns -- that
function's return value is exactly what gets cached, and caching who
asked for a report (and when) would mean every cache HIT re-attributes
the report to whoever happened to trigger the original cache MISS. Both
fields are stamped fresh, per request, in _finalize_report below, after
the cache lookup -- a JSON/PDF/CSV response's own "generated by/at"
header is always accurate for the request that produced it, cached data
or not.
"""
from __future__ import annotations

import asyncio
from datetime import date, datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Query
from fastapi.responses import Response

from control_center.analytics import cache
from control_center.compliance import audit_log, csv_export, pdf, service
from control_center.core.auth import require_permission

router = APIRouter(prefix="/compliance", tags=["compliance"])

# Same string omnibioai-auth's app/rbac.py::MANAGE_ALL_ORGS,
# omnibioai-billing's core/iam.py, and control-center's own
# analytics/permissions.py already check -- one ecosystem-wide meaning,
# not redefined per module.
MANAGE_ALL_ORGS = "manage_all_orgs"

_CACHE_TTL_SECONDS = 3600  # task brief: "Cache report 1hr (expensive query)"

_require_platform_admin = require_permission(MANAGE_ALL_ORGS)


def _cache_key(organization_id: int, from_date: date, to_date: date) -> str:
    return f"compliance:hipaa-report:{organization_id}:{from_date.isoformat()}:{to_date.isoformat()}"


def _generated_by(payload: dict) -> str:
    return payload.get("email") or payload.get("sub") or "unknown"


def _validate_range(from_date: date, to_date: date) -> None:
    if from_date > to_date:
        raise HTTPException(400, "from_date must be on or before to_date")


async def _fetch_cached_report(*, org_id: int, from_date: date, to_date: date, authorization: Optional[str]) -> dict:
    """Returns the cacheable report body -- summary/sections/
    sources_unavailable/truncated, nothing request-specific. See this
    module's own docstring for why generated_by/generated_at are
    deliberately excluded from what this function (and therefore the
    cache) returns.
    """
    key = _cache_key(org_id, from_date, to_date)
    return await cache.get_or_set_async(
        key,
        "hipaa_report",
        lambda: service.build_report(
            organization_id=org_id, from_date=from_date, to_date=to_date, authorization=authorization,
        ),
        ttl=_CACHE_TTL_SECONDS,
    )


async def _build_report(
    *, org_id: int, from_date: date, to_date: date, authorization: Optional[str], generated_by: str,
) -> dict:
    """The cached body plus fresh, request-specific provenance -- the
    shape every one of the three routes actually needs. 404s on a
    confirmed-nonexistent organization (service.OrganizationNotFoundError
    -- a real 404 from omnibioai-auth, not a network hiccup); any other
    downstream failure degrades gracefully instead (see
    sources_unavailable in the returned body)."""
    try:
        data = await _fetch_cached_report(org_id=org_id, from_date=from_date, to_date=to_date, authorization=authorization)
    except service.OrganizationNotFoundError as e:
        raise HTTPException(404, str(e))
    return {
        **data,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": generated_by,
    }


def _filename_stem(org_id: int, from_date: date, to_date: date) -> str:
    return f"hipaa-report-org{org_id}-{from_date.isoformat()}-to-{to_date.isoformat()}"


@router.get("/hipaa-report")
async def hipaa_report(
    from_date: date = Query(...),
    to_date: date = Query(...),
    org_id: int = Query(...),
    authorization: Optional[str] = Header(default=None),
    admin: dict = Depends(_require_platform_admin),
) -> dict:
    _validate_range(from_date, to_date)
    generated_by = _generated_by(admin)
    report = await _build_report(
        org_id=org_id, from_date=from_date, to_date=to_date, authorization=authorization, generated_by=generated_by,
    )
    audit_log.log_report_access(
        actor=generated_by, organization_id=org_id, from_date=from_date, to_date=to_date, report_format="json",
    )
    return report


@router.get("/hipaa-report/pdf")
async def hipaa_report_pdf(
    from_date: date = Query(...),
    to_date: date = Query(...),
    org_id: int = Query(...),
    authorization: Optional[str] = Header(default=None),
    admin: dict = Depends(_require_platform_admin),
) -> Response:
    _validate_range(from_date, to_date)
    generated_by = _generated_by(admin)
    context = await _build_report(
        org_id=org_id, from_date=from_date, to_date=to_date, authorization=authorization, generated_by=generated_by,
    )
    # WeasyPrint's layout pass is a real, blocking CPU cost (not I/O) --
    # off the event loop via run_in_executor, the same pattern
    # api/routes_llm.py's own count_abstracts/list_indexed_domains already
    # use for their blocking filesystem walks, so this request doesn't
    # stall every other concurrent request this process is serving.
    loop = asyncio.get_event_loop()
    pdf_bytes = await loop.run_in_executor(None, pdf.render_report_pdf, context)

    audit_log.log_report_access(
        actor=generated_by, organization_id=org_id, from_date=from_date, to_date=to_date, report_format="pdf",
    )

    filename = f"{_filename_stem(org_id, from_date, to_date)}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/hipaa-report/csv")
async def hipaa_report_csv(
    from_date: date = Query(...),
    to_date: date = Query(...),
    org_id: int = Query(...),
    authorization: Optional[str] = Header(default=None),
    admin: dict = Depends(_require_platform_admin),
) -> Response:
    _validate_range(from_date, to_date)
    generated_by = _generated_by(admin)
    context = await _build_report(
        org_id=org_id, from_date=from_date, to_date=to_date, authorization=authorization, generated_by=generated_by,
    )
    # Cheap (plain string formatting, no layout engine) unlike the PDF
    # route above -- no run_in_executor needed here.
    csv_text = csv_export.render_report_csv(context)

    audit_log.log_report_access(
        actor=generated_by, organization_id=org_id, from_date=from_date, to_date=to_date, report_format="csv",
    )

    filename = f"{_filename_stem(org_id, from_date, to_date)}.csv"
    return Response(
        content=csv_text,
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
