import { useCallback, useEffect, useState } from 'react'
import { fetchSafeAuditEvents, formatSafeEventType, type SafeAuditEvent, type SafeAuditResponse } from '../../securityAudit'
import { Card, DataTable, ErrorState, LoadingState, Pagination, SectionHeader, StatCard } from '../../components/ui'
import StatusBadge from '../../components/StatusBadge'
import { formatDate, classifyAuthError } from '../../format'
import { fetchPlatformOrgs, type PlatformOrgSummary } from '../../organizations'
import { getSessionUser, hasPlatformAdminAccess } from '../../auth'

const PAGE_SIZE = 20
const inputStyle: React.CSSProperties = { padding: '7px 9px', border: '1px solid var(--border)', borderRadius: 8, background: 'var(--surface)', color: 'var(--text)', fontSize: 12 }

function Detail({ event, onClose }: { event: SafeAuditEvent; onClose: () => void }) {
  return <Card style={{ marginTop: 16 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h2 style={{ fontSize: 14 }}>Event detail</h2><button type="button" onClick={onClose} aria-label="Close event detail">Close</button></div><dl style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 12, fontSize: 12 }}>
    {([['Event ID', event.event_id], ['Trace ID', event.metadata.trace_id], ['Request ID', event.metadata.request_id], ['Workflow ID', event.metadata.workflow_id], ['Run ID', event.metadata.run_id], ['Resource', [event.metadata.resource_type, event.metadata.resource_id].filter(Boolean).join(' ')], ['Backend', event.metadata.backend]] as const).map(([label, value]) => <div key={label}><dt style={{ color: 'var(--muted)', fontSize: 10, textTransform: 'uppercase' }}>{label}</dt><dd style={{ margin: '3px 0 0', wordBreak: 'break-word' }}>{value || '—'}</dd></div>)}
  </dl><p style={{ color: 'var(--muted)', fontSize: 11, marginBottom: 0 }}>Only the Security Audit safe metadata projection is shown. Raw context and signing material are never available here.</p></Card>
}

function SourceSummary({ data }: { data: SafeAuditResponse }) {
  return <><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(145px,1fr))', gap: 12, marginBottom: 16 }}><StatCard label="Matching events" value={data.total} /><StatCard label="Source" value={data.source_availability} accent={data.source_availability === 'AVAILABLE' ? 'green' : 'amber'} /><StatCard label="Freshness" value={data.freshness.status} /><StatCard label="Retention" value={data.retention.status} /></div><Card style={{ marginBottom: 16, fontSize: 11, color: 'var(--muted)' }}>Generated {formatDate(data.generated_at)} · Source checked {formatDate(data.source_checked_at)}{data.warnings.length > 0 && <div style={{ marginTop: 6 }}>Warnings: {data.warnings.join(', ')}</div>}</Card></>
}

export default function AuditExplorerPage() {
  const platformWide = hasPlatformAdminAccess(); const session = getSessionUser()
  const [data, setData] = useState<SafeAuditResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [page, setPage] = useState(1); const [selected, setSelected] = useState<SafeAuditEvent | null>(null); const [orgs, setOrgs] = useState<PlatformOrgSummary[]>([])
  const [filters, setFilters] = useState({ service: '', eventType: '', userId: '', decision: '', integrityStatus: '', organizationId: '', fromTimestamp: '', toTimestamp: '' })
  const update = (key: keyof typeof filters, value: string) => { setFilters(current => ({ ...current, [key]: value })); setPage(1) }
  const load = useCallback(() => { setLoading(true); setError(null); fetchSafeAuditEvents({ ...filters, page, pageSize: PAGE_SIZE, integrityStatus: filters.integrityStatus as never }).then(setData).catch((e: unknown) => { const message = e instanceof Error ? e.message : ''; const kind = classifyAuthError(message); setError(kind === 'session' ? 'Your session has expired.' : kind === 'denied' ? 'You are not authorized to view Security Audit events.' : message.endsWith(' 422') ? 'The selected filters are not valid.' : 'Security Audit source is unavailable.') }).finally(() => setLoading(false)) }, [filters, page])
  useEffect(() => { load() }, [load]); useEffect(() => { if (platformWide) fetchPlatformOrgs({ pageSize: 100 }).then(r => setOrgs(r.items)).catch(() => {}) }, [platformWide])
  const clear = () => { setFilters({ service: '', eventType: '', userId: '', decision: '', integrityStatus: '', organizationId: '', fromTimestamp: '', toTimestamp: '' }); setPage(1) }
  return <div><SectionHeader title="Audit Explorer" description="Read-only evidence from the Security Audit durable event store." actions={<button type="button" onClick={load} disabled={loading}>Refresh</button>} />
    {loading && !data ? <LoadingState label="Loading Security Audit events…" /> : error && !data ? <ErrorState message={error} onRetry={load} /> : data && <><SourceSummary data={data} /><Card style={{ marginBottom: 16 }}><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'end' }}>
      {([['service', 'Service'], ['eventType', 'Event type'], ['userId', 'Actor/user'], ['decision', 'Decision']] as const).map(([key, label]) => <label key={key} style={{ display: 'grid', gap: 4, fontSize: 11 }}>{label}<input aria-label={label} style={inputStyle} value={filters[key]} onChange={e => update(key, e.target.value)} /></label>)}
      <label style={{ display: 'grid', gap: 4, fontSize: 11 }}>Integrity<select aria-label="Integrity" style={inputStyle} value={filters.integrityStatus} onChange={e => update('integrityStatus', e.target.value)}><option value="">All</option>{['valid', 'invalid', 'unsigned', 'unknown'].map(v => <option key={v}>{v}</option>)}</select></label>
      {platformWide && <label style={{ display: 'grid', gap: 4, fontSize: 11 }}>Organization<select aria-label="Organization" style={inputStyle} value={filters.organizationId} onChange={e => update('organizationId', e.target.value)}><option value="">All organizations</option>{orgs.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
      {(['fromTimestamp', 'toTimestamp'] as const).map(key => <label key={key} style={{ display: 'grid', gap: 4, fontSize: 11 }}>{key === 'fromTimestamp' ? 'From' : 'To'}<input aria-label={key === 'fromTimestamp' ? 'From timestamp' : 'To timestamp'} type="datetime-local" style={inputStyle} value={filters[key]} onChange={e => update(key, e.target.value ? new Date(e.target.value).toISOString() : '')} /></label>)}
      <button type="button" onClick={clear}>Clear</button></div><div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 10 }}>{platformWide ? 'Platform-wide access. Organization filtering narrows results only; it does not establish authorization.' : `Organization-scoped access${session?.orgId ? ` · organization ${session.orgId}` : ''}. Tenant scope is verified by Security Audit.`}</div></Card>
      {data.source_availability !== 'AVAILABLE' && <Card style={{ marginBottom: 16 }}><StatusBadge status={data.source_availability.toLowerCase()} /> <span style={{ marginLeft: 8 }}>{data.source_availability === 'UNAVAILABLE' ? 'Security Audit source is unavailable.' : 'Security Audit returned a partial or unknown source state.'}</span></Card>}
      {error && <ErrorState message={error} onRetry={load} />} {!error && <><DataTable rows={data.items} rowKey={e => e.event_id} emptyLabel="AVAILABLE · 0 matching events" columns={[{ key: 'timestamp', header: 'Timestamp', render: e => formatDate(e.timestamp) }, { key: 'service', header: 'Service', render: () => '—' }, { key: 'event', header: 'Event type', render: e => formatSafeEventType(e.event_type) }, { key: 'actor', header: 'Actor', render: e => e.actor || '—' }, { key: 'org', header: 'Organization', render: e => e.organization_id || '—' }, { key: 'scope', header: 'Tenant scope', render: e => e.tenant_scope }, { key: 'decision', header: 'Decision', render: e => e.decision || '—' }, { key: 'integrity', header: 'Integrity', render: e => <StatusBadge status={e.integrity} /> }, { key: 'detail', header: 'Detail', render: e => <button type="button" onClick={() => setSelected(e)} aria-expanded={selected?.event_id === e.event_id}>View</button> }]} /><Pagination page={data.page} totalPages={data.total_pages} onPage={setPage} /></>}</>}{selected && <Detail event={selected} onClose={() => setSelected(null)} />}</div>
}
